userProfile = struct();
userProfile.Username = 'johndoe';
userProfile.Username_ = @(parent) uieditfield(parent, 'text', ...
    'Placeholder', 'Enter username...');

userProfile.Bio = 'Tell us about yourself';
userProfile.Bio_ = @(parent) uitextarea(parent, ...
    'Placeholder', 'Write your bio here...');

userProfile.SkillLevel = 5;
userProfile.SkillLevel_ = @(parent) uislider(parent, ...
    'Limits', [1 10], ...
    'MajorTicks', 1:10, ...
    'MinorTicks', []);

userProfile.NotifyByEmail = true;
userProfile.NotifyBySMS = false;

updatedProfile = uiform(userProfile, ...
    "Title", "User Profile", ...
    "Description", "Customize your profile settings", ...
    "Height", 450);